name: Daily DaddyLive Scraper

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Specify a Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper script
      run: python daddylive_scraper.py

    - name: Upload M3U playlist as artifact (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: daddylive-playlist
        path: daddylive_247_channels.m3u
